In [2]:
import numpy as np
import pandas as pd

In [3]:
lefty_df = pd.read_csv("Batters_vs_LHP_CSV.csv")
righty_df = pd.read_csv("Batters_vs_RHP_CSV.csv")

In [4]:
lefty_df.head(10)

,Year,Name,Team,G,PA,HR,R,RBI,SB,BB%,K%,ISO,BABIP,AVG,OBP,SLG,wOBA,wRC+
0,2025,Carlos Santana,2 Tms,74,148,4,13,19,2,11.50%,17.60%,0.115,0.257,0.231,0.318,0.346,0.294,89
1,2025,Freddie Freeman,LAD,98,175,8,20,19,2,8.00%,24.00%,0.222,0.339,0.285,0.349,0.506,0.364,136
2,2025,Wilmer Flores,SFG,70,151,6,14,20,1,6.00%,19.20%,0.150,0.255,0.236,0.285,0.386,0.292,88
3,2025,Salvador Perez,KCR,76,144,2,5,14,0,4.20%,20.10%,0.096,0.257,0.213,0.257,0.309,0.238,45
4,2025,Miguel Rojas,LAD,72,135,6,21,16,2,9.60%,12.60%,0.221,0.303,0.295,0.363,0.516,0.376,143
5,2025,Paul Goldschmidt,NYY,85,168,7,26,16,3,10.10%,11.30%,0.235,0.350,0.336,0.411,0.570,0.412,169
6,2025,Starling Marte,NYM,69,147,4,19,12,3,7.50%,20.40%,0.143,0.310,0.263,0.327,0.406,0.321,109
7,2025,Andrew McCutchen,PIT,72,150,3,13,19,0,12.00%,24.00%,0.122,0.344,0.267,0.353,0.389,0.322,104
8,2025,Jose Iglesias,SDP,71,137,1,16,12,1,10.20%,19.70%,0.108,0.293,0.233,0.319,0.342,0.296,92
9,2025,Randal Grichuk,2 Tms,97,183,7,20,18,0,6.00%,24.00%,0.203,0.264,0.227,0.273,0.430,0.300,89

In [5]:
righty_df.head(10)

,Year,Name,Team,G,PA,HR,R,RBI,SB,BB%,K%,ISO,BABIP,AVG,OBP,SLG,wOBA,wRC+
0,2025,Freddie Freeman,LAD,142,452,16,61,71,4,10.20%,19.00%,0.201,0.343,0.299,0.374,0.500,0.372,141
1,2025,Jose Altuve,HOU,152,530,19,63,61,9,8.10%,15.30%,0.170,0.283,0.266,0.329,0.436,0.329,112
2,2025,Salvador Perez,KCR,152,497,28,49,86,0,4.40%,19.30%,0.243,0.249,0.243,0.291,0.486,0.331,110
3,2025,Paul Goldschmidt,NYY,123,366,3,50,29,2,5.20%,22.10%,0.082,0.314,0.247,0.289,0.329,0.273,74
4,2025,Andrew McCutchen,PIT,128,401,10,38,38,1,12.20%,20.40%,0.130,0.270,0.228,0.326,0.358,0.304,92
5,2025,Mike Trout,LAA,127,451,23,60,54,2,16.40%,30.80%,0.221,0.303,0.235,0.369,0.456,0.355,128
6,2025,Marcell Ozuna,ATL,143,451,18,48,60,0,14.20%,24.60%,0.180,0.280,0.235,0.347,0.415,0.335,115
7,2025,Christian Yelich,MIL,142,438,25,64,71,9,10.70%,25.10%,0.230,0.320,0.274,0.356,0.504,0.367,138
8,2025,Manny Machado,SDP,150,491,15,58,72,8,7.10%,19.30%,0.164,0.328,0.284,0.336,0.448,0.339,121
9,2025,Willson Contreras,STL,129,418,15,52,56,3,6.70%,25.40%,0.183,0.309,0.251,0.333,0.433,0.335,117

In [6]:
def percent_to_decimal(string: str) -> float:
    num_str = ""
    for char in string:
        if char != "%":
            num_str += char
        else:
            break
    num = float(num_str)
    return num/100

In [7]:
def list_percent_to_decimal(string_list: list) -> list:
    new_list = []
    for elem in string_list:
        new_list.append(percent_to_decimal(elem))
    return new_list

In [8]:
lefty_df["BB%"] = list_percent_to_decimal(list(lefty_df["BB%"]))
lefty_df["K%"] = list_percent_to_decimal(list(lefty_df["K%"]))
righty_df["BB%"] = list_percent_to_decimal(list(righty_df["BB%"]))
righty_df["K%"] = list_percent_to_decimal(list(righty_df["K%"]))

In [9]:
lefty_df.head(10)

,Year,Name,Team,G,PA,HR,R,RBI,SB,BB%,K%,ISO,BABIP,AVG,OBP,SLG,wOBA,wRC+
0,2025,Carlos Santana,2 Tms,74,148,4,13,19,2,0.115,0.176,0.115,0.257,0.231,0.318,0.346,0.294,89
1,2025,Freddie Freeman,LAD,98,175,8,20,19,2,0.080,0.240,0.222,0.339,0.285,0.349,0.506,0.364,136
2,2025,Wilmer Flores,SFG,70,151,6,14,20,1,0.060,0.192,0.150,0.255,0.236,0.285,0.386,0.292,88
3,2025,Salvador Perez,KCR,76,144,2,5,14,0,0.042,0.201,0.096,0.257,0.213,0.257,0.309,0.238,45
4,2025,Miguel Rojas,LAD,72,135,6,21,16,2,0.096,0.126,0.221,0.303,0.295,0.363,0.516,0.376,143
5,2025,Paul Goldschmidt,NYY,85,168,7,26,16,3,0.101,0.113,0.235,0.350,0.336,0.411,0.570,0.412,169
6,2025,Starling Marte,NYM,69,147,4,19,12,3,0.075,0.204,0.143,0.310,0.263,0.327,0.406,0.321,109
7,2025,Andrew McCutchen,PIT,72,150,3,13,19,0,0.120,0.240,0.122,0.344,0.267,0.353,0.389,0.322,104
8,2025,Jose Iglesias,SDP,71,137,1,16,12,1,0.102,0.197,0.108,0.293,0.233,0.319,0.342,0.296,92
9,2025,Randal Grichuk,2 Tms,97,183,7,20,18,0,0.060,0.240,0.203,0.264,0.227,0.273,0.430,0.300,89

In [10]:
righty_df.head(10)

,Year,Name,Team,G,PA,HR,R,RBI,SB,BB%,K%,ISO,BABIP,AVG,OBP,SLG,wOBA,wRC+
0,2025,Freddie Freeman,LAD,142,452,16,61,71,4,0.102,0.190,0.201,0.343,0.299,0.374,0.500,0.372,141
1,2025,Jose Altuve,HOU,152,530,19,63,61,9,0.081,0.153,0.170,0.283,0.266,0.329,0.436,0.329,112
2,2025,Salvador Perez,KCR,152,497,28,49,86,0,0.044,0.193,0.243,0.249,0.243,0.291,0.486,0.331,110
3,2025,Paul Goldschmidt,NYY,123,366,3,50,29,2,0.052,0.221,0.082,0.314,0.247,0.289,0.329,0.273,74
4,2025,Andrew McCutchen,PIT,128,401,10,38,38,1,0.122,0.204,0.130,0.270,0.228,0.326,0.358,0.304,92
5,2025,Mike Trout,LAA,127,451,23,60,54,2,0.164,0.308,0.221,0.303,0.235,0.369,0.456,0.355,128
6,2025,Marcell Ozuna,ATL,143,451,18,48,60,0,0.142,0.246,0.180,0.280,0.235,0.347,0.415,0.335,115
7,2025,Christian Yelich,MIL,142,438,25,64,71,9,0.107,0.251,0.230,0.320,0.274,0.356,0.504,0.367,138
8,2025,Manny Machado,SDP,150,491,15,58,72,8,0.071,0.193,0.164,0.328,0.284,0.336,0.448,0.339,121
9,2025,Willson Contreras,STL,129,418,15,52,56,3,0.067,0.254,0.183,0.309,0.251,0.333,0.433,0.335,117

In [11]:
all_batters_df = pd.merge(lefty_df, righty_df, how = "inner", on = ["Year", "Name", "Team"])
all_batters_df.head(10)

,Year,Name,Team,G_x,PA_x,HR_x,R_x,RBI_x,SB_x,BB%_x,...,SB_y,BB%_y,K%_y,ISO_y,BABIP_y,AVG_y,OBP_y,SLG_y,wOBA_y,wRC+_y
0,2025,Freddie Freeman,LAD,98,175,8,20,19,2,0.080,...,4,0.102,0.190,0.201,0.343,0.299,0.374,0.500,0.372,141
1,2025,Salvador Perez,KCR,76,144,2,5,14,0,0.042,...,0,0.044,0.193,0.243,0.249,0.243,0.291,0.486,0.331,110
2,2025,Paul Goldschmidt,NYY,85,168,7,26,16,3,0.101,...,2,0.052,0.221,0.082,0.314,0.247,0.289,0.329,0.273,74
3,2025,Andrew McCutchen,PIT,72,150,3,13,19,0,0.120,...,1,0.122,0.204,0.130,0.270,0.228,0.326,0.358,0.304,92
4,2025,Marcell Ozuna,ATL,68,141,3,13,8,0,0.213,...,0,0.142,0.246,0.180,0.280,0.235,0.347,0.415,0.335,115
5,2025,Christian Yelich,MIL,101,206,4,24,32,7,0.083,...,9,0.107,0.251,0.230,0.320,0.274,0.356,0.504,0.367,138
6,2025,Manny Machado,SDP,81,187,12,33,23,6,0.107,...,8,0.071,0.193,0.164,0.328,0.284,0.336,0.448,0.339,121
7,2025,Willson Contreras,STL,68,145,5,18,24,2,0.110,...,3,0.067,0.254,0.183,0.309,0.251,0.333,0.433,0.335,117
8,2025,Nick Castellanos,PHI,88,188,5,16,25,1,0.059,...,3,0.052,0.209,0.152,0.294,0.254,0.294,0.406,0.303,91
9,2025,J.T. Realmuto,PHI,87,166,3,16,11,3,0.054,...,5,0.068,0.224,0.130,0.341,0.277,0.337,0.406,0.326,107

In [12]:
all_batters_df.drop(columns = ["G_x", "G_y"], inplace = True)
all_batters_df.drop(columns = ["SB_x", "SB_y"], inplace = True)
all_batters_df.drop(columns = ["R_x", "R_y", "RBI_x", "RBI_y"], inplace = True)

In [13]:
all_batters_df.iloc[0]

Year                  2025
Name       Freddie Freeman
Team                   LAD
PA_x                   175
HR_x                     8
BB%_x                 0.08
K%_x                  0.24
ISO_x                0.222
BABIP_x              0.339
AVG_x                0.285
OBP_x                0.349
SLG_x                0.506
wOBA_x               0.364
wRC+_x                 136
PA_y                   452
HR_y                    16
BB%_y                0.102
K%_y                  0.19
ISO_y                0.201
BABIP_y              0.343
AVG_y                0.299
OBP_y                0.374
SLG_y                  0.5
wOBA_y               0.372
wRC+_y                 141
Name: 0, dtype: object

In [14]:
# Renaming:  _x - from lefty dataframe, _y from righty dataframe
all_batters_df.rename(columns = {"PA_x": "PA_left", "HR_x": "HR_left", "BB%_x": "BB%_left", "K%_x": "K%_left", 
                       "ISO_x": "ISO_left", "BABIP_x": "BABIP_left", "AVG_x": "AVG_left", "OBP_x": "OBP_left",
                       "SLG_x": "SLG_left", "wOBA_x": "wOBA_left", "wRC+_x": "wRC+_left", "PA_y": "PA_right", 
                       "HR_y": "HR_right", "BB%_y": "BB%_right", "K%_y": "K%_right", "ISO_y": "ISO_right", "BABIP_y": "BABIP_right", 
                       "AVG_y": "AVG_right", "OBP_y": "OBP_right", "SLG_y": "SLG_right", 
                       "wOBA_y": "wOBA_right", "wRC+_y": "wRC+_right"}, inplace = True)

In [15]:
all_batters_df.head(10)

,Year,Name,Team,PA_left,HR_left,BB%_left,K%_left,ISO_left,BABIP_left,AVG_left,...,HR_right,BB%_right,K%_right,ISO_right,BABIP_right,AVG_right,OBP_right,SLG_right,wOBA_right,wRC+_right
0,2025,Freddie Freeman,LAD,175,8,0.080,0.240,0.222,0.339,0.285,...,16,0.102,0.190,0.201,0.343,0.299,0.374,0.500,0.372,141
1,2025,Salvador Perez,KCR,144,2,0.042,0.201,0.096,0.257,0.213,...,28,0.044,0.193,0.243,0.249,0.243,0.291,0.486,0.331,110
2,2025,Paul Goldschmidt,NYY,168,7,0.101,0.113,0.235,0.350,0.336,...,3,0.052,0.221,0.082,0.314,0.247,0.289,0.329,0.273,74
3,2025,Andrew McCutchen,PIT,150,3,0.120,0.240,0.122,0.344,0.267,...,10,0.122,0.204,0.130,0.270,0.228,0.326,0.358,0.304,92
4,2025,Marcell Ozuna,ATL,141,3,0.213,0.234,0.128,0.280,0.220,...,18,0.142,0.246,0.180,0.280,0.235,0.347,0.415,0.335,115
5,2025,Christian Yelich,MIL,206,4,0.083,0.277,0.102,0.328,0.242,...,25,0.107,0.251,0.230,0.320,0.274,0.356,0.504,0.367,138
6,2025,Manny Machado,SDP,187,12,0.107,0.193,0.244,0.246,0.250,...,15,0.071,0.193,0.164,0.328,0.284,0.336,0.448,0.339,121
7,2025,Willson Contreras,STL,145,5,0.110,0.248,0.211,0.349,0.276,...,15,0.067,0.254,0.183,0.309,0.251,0.333,0.433,0.335,117
8,2025,Nick Castellanos,PHI,188,5,0.059,0.261,0.145,0.306,0.243,...,12,0.052,0.209,0.152,0.294,0.254,0.294,0.406,0.303,91
9,2025,J.T. Realmuto,PHI,166,3,0.054,0.259,0.123,0.275,0.213,...,9,0.068,0.224,0.130,0.341,0.277,0.337,0.406,0.326,107

In [16]:
# Convert OBP and SLG to OPS
all_batters_df["OPS_left"] = all_batters_df["OBP_left"] + all_batters_df["SLG_left"]
all_batters_df["OPS_right"] = all_batters_df["OBP_right"] + all_batters_df["SLG_right"]
# Remove the OBP and SLG
all_batters_df.drop(columns = ["OBP_left", "SLG_left", "OBP_right", "SLG_right"], inplace = True)

In [17]:
all_batters_df.head(10)

,Year,Name,Team,PA_left,HR_left,BB%_left,K%_left,ISO_left,BABIP_left,AVG_left,...,HR_right,BB%_right,K%_right,ISO_right,BABIP_right,AVG_right,wOBA_right,wRC+_right,OPS_left,OPS_right
0,2025,Freddie Freeman,LAD,175,8,0.080,0.240,0.222,0.339,0.285,...,16,0.102,0.190,0.201,0.343,0.299,0.372,141,0.855,0.874
1,2025,Salvador Perez,KCR,144,2,0.042,0.201,0.096,0.257,0.213,...,28,0.044,0.193,0.243,0.249,0.243,0.331,110,0.566,0.777
2,2025,Paul Goldschmidt,NYY,168,7,0.101,0.113,0.235,0.350,0.336,...,3,0.052,0.221,0.082,0.314,0.247,0.273,74,0.981,0.618
3,2025,Andrew McCutchen,PIT,150,3,0.120,0.240,0.122,0.344,0.267,...,10,0.122,0.204,0.130,0.270,0.228,0.304,92,0.742,0.684
4,2025,Marcell Ozuna,ATL,141,3,0.213,0.234,0.128,0.280,0.220,...,18,0.142,0.246,0.180,0.280,0.235,0.335,115,0.732,0.762
5,2025,Christian Yelich,MIL,206,4,0.083,0.277,0.102,0.328,0.242,...,25,0.107,0.251,0.230,0.320,0.274,0.367,138,0.660,0.860
6,2025,Manny Machado,SDP,187,12,0.107,0.193,0.244,0.246,0.250,...,15,0.071,0.193,0.164,0.328,0.284,0.339,121,0.826,0.784
7,2025,Willson Contreras,STL,145,5,0.110,0.248,0.211,0.349,0.276,...,15,0.067,0.254,0.183,0.309,0.251,0.335,117,0.863,0.766
8,2025,Nick Castellanos,PHI,188,5,0.059,0.261,0.145,0.306,0.243,...,12,0.052,0.209,0.152,0.294,0.254,0.303,91,0.680,0.700
9,2025,J.T. Realmuto,PHI,166,3,0.054,0.259,0.123,0.275,0.213,...,9,0.068,0.224,0.130,0.341,0.277,0.326,107,0.600,0.743

In [62]:
# Add wOBA column (no lefty-righty splits)
woba_df = pd.read_csv("all_batters_WOBA.csv")

In [64]:
def swap_name(string_list: list) -> list:
    """Given a list of names separated by commas, reformat them from last, first to first last"""
    newList = list([])
    for string in string_list:
        first = ""
        last = ""
        i = 0
        while string[i:i + 1] != ",":
            last += string[i:i + 1]
            i += 1
        i += 1
        while i < len(string):
            first += string[i:i + 1]
            i += 1
        newList.append(first.strip()+" "+last.strip())
    return newList

In [75]:
#woba_df["Name"] = swap_name(list(woba_df["Name"]))

In [77]:
woba_df.head(10)

             Name  player_id  Year   wOBA
0    Torii Hunter     116338  2015  0.304
1     David Ortiz     120074  2015  0.379
2  Alex Rodriguez     121347  2015  0.361
3  Aramis Ramirez     133380  2015  0.309
4   Adrian Beltré     134181  2015  0.337
5  Carlos Beltrán     136860  2015  0.346
6   Jimmy Rollins     276519  2015  0.283
7   Albert Pujols     405395  2015  0.333
8     Marlon Byrd     407781  2015  0.317
9       Joe Mauer     408045  2015  0.311

In [79]:
woba_df.drop(columns = ["player_id"], inplace = True)

In [81]:
woba_df.head(10)

             Name  Year   wOBA
0    Torii Hunter  2015  0.304
1     David Ortiz  2015  0.379
2  Alex Rodriguez  2015  0.361
3  Aramis Ramirez  2015  0.309
4   Adrian Beltré  2015  0.337
5  Carlos Beltrán  2015  0.346
6   Jimmy Rollins  2015  0.283
7   Albert Pujols  2015  0.333
8     Marlon Byrd  2015  0.317
9       Joe Mauer  2015  0.311

In [83]:
all_batters_df = pd.merge(all_batters_df, woba_df, how = "inner", on = ["Year", "Name"])

In [85]:
# Save it to use in different file
all_batters_df.to_csv("all_batters.csv", index = False)